In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

In [4]:
%pip install otter-grader

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://packagemanager.posit.co/pypi/latest/simple
Collecting otter-grader
  Downloading https://p3m.dev/pypi/latest/packages/otter-grader/aad08cba3653b203c4bce5b2b40df675811ec13735207f2deda8d128120fd24a/otter_grader-7.0.0-py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: click<9.0.0,>=8.1.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (8.4.2)
Collecting dill>=0.3.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/dill/1e1ce33e978ae97fcfcff5638477032b801c46c7c65cf717f95fbc2248f79a9d/dill-0.4.1-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.0/120.0 kB 13.8 MB/s eta 0:00:00
Collecting fica>=0.4.1 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/fica/d5cb066cfdc67715f99efdbce2fdaeb0c92f67b5d2aaf0740397b984731de2d5/fica-0.4.1-py3-none-any.whl (13 kB)
Collecting ipylab<2.0.0,>=1.0.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/ipylab/a24c29aeb7d6d8b26c150794ef30c8d9ac2e387c47ea49f9afd8fa19dcd07b62/ipylab-1.1.0-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 11.4 MB/s eta 0:00:00
Requirement already satisfied: ipython in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (9.16.1)
Collecting ipywidgets<9.0.0,>=8.1.5 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/ipywidgets/f2b8cbcaae10252b809fbe4d7470db75c09b769a32cbf816d20e5ca6d3c5a79d/ipywidgets-8.1.9-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.1/140.1 kB 15.4 MB/s eta 0:00:00
Requirement already satisfied: jinja2<4.0,>=3.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (3.1.6)
Collecting jupytext<2.0.0,>=1.19.3 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jupytext/eb725d66841f1a91707bdcf4703b194a53151a060ecb3fd31d78139cc9ec090a/jupytext-1.19.6-py3-none-any.whl (230 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.8/230.8 kB 23.1 MB/s eta 0:00:00
Collecting nbconvert>=6.0.0 (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbconvert/aa85c087b435e7bf1ffd03319f658e285f2b89eccab33bc1ba7025495ab3e7c8/nbconvert-7.17.1-py3-none-any.whl (261 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.9/261.9 kB 35.5 MB/s eta 0:00:00
Collecting nbformat>=5.0.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbformat/cc6698fa75f4fab8755ead786317815f13a6fee3b53311c0abb1a8b51d52f7ec/nbformat-5.11.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 590.0 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pandas>=2.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (2.3.3)
Collecting python-frontmatter<2.0.0,>=1.3.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/python-frontmatter/9f7dd9260bec99044219159a329f64f039087f9d1a2124c9442556f2fe6f82ec/python_frontmatter-1.3.0-py3-none-any.whl (10 kB)
Collecting python-on-whales<1.0.0,>=0.72.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/python-on-whales/6d5f81f56d0f95fd311a7cce29a01a1a60841074e4936000dc5f2dc9a7ffafac/python_on_whales-0.81.0-py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.2/119.2 kB 13.2 MB/s eta 0:00:00
Collecting pyyaml<7,>=6 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pyyaml/b8bb0864c5a28024fac8a632c443c87c5aa6f215c0b126c449ae1a150412f31d/pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (806 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 806.6/806.6 kB 2.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: requests<3.0,>=2.31 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (2.34.2)
Collecting wrapt<2.0.0,>=1.16.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/wrapt/b32888aad8b6e68f83a8fdccbf3165f5469702a7544472bdf41f582970ed3311/wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 kB 613.4 kB/s eta 0:00:00a 0:00:01
Collecting docutils (from fica>=0.4.1->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/docutils/25d013af9bf23bc1c7b2b093dff4208166c53a94786c9e447808335ef1185fea/docutils-0.23-py3-none-any.whl (634 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.7/634.7 kB 41.5 MB/s eta 0:00:00
Collecting sphinx (from fica>=0.4.1->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/sphinx/5bebc595a5e943ea248b99c13814c1c5e10b3ece718976824ffa7959ff95fffb/sphinx-9.0.4-py3-none-any.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 9.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: comm>=0.1.3 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (5.16.1)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets<9.0.0,>=8.1.5->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/widgetsnbextension/a31a8774885b96fe825462f5d6496166f0c7cae111195b6465c801d230eb5a4e/widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 128.9 MB/s eta 0:00:00
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets<9.0.0,>=8.1.5->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jupyterlab-widgets/40ac1e9955acf116c4d995d9bfa082d86ad9ec6d91c4f134827cf5e0a5eb75e0/jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.3/217.3 kB 21.9 MB/s eta 0:00:00
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (3.0.53)
Requirement already satisfied: psutil>=7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jinja2<4.0,>=3.1->otter-grader) (3.0.3)
Collecting markdown-it-py>=1.0 (from jupytext<2.0.0,>=1.19.3->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/markdown-it-py/9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a/markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 693.8 kB/s eta 0:00:00a 0:00:01
Collecting mdit-py-plugins (from jupytext<2.0.0,>=1.19.3->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/mdit-py-plugins/214c82fb2ac524472ab6a5bcab1de80f73b50443e187f401bfd77efbc7c6481d/mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.7/66.7 kB 8.8 MB/s eta 0:00:00
Requirement already satisfied: packaging in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jupytext<2.0.0,>=1.19.3->otter-grader) (26.3)
Collecting beautifulsoup4 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/beautifulsoup4/d6f88de62e1d4e38ecb1077eb9724cd0eff29d2a08ca16a401e9b9e93f117cf9/beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.9/109.9 kB 12.9 MB/s eta 0:00:00
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/bleach/4b6b6a54fff2e69a3dde9d21cc6301220bee3c3cb792187d11403fd795031081/bleach-6.4.0-py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.1/165.1 kB 17.8 MB/s eta 0:00:00
Collecting defusedxml (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/defusedxml/a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61/defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: jupyter-core>=4.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (5.9.1)
Collecting jupyterlab-pygments (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jupyterlab-pygments/841a89020971da1d8693f1a99997aefc5dc424bb1b251fd6322462a1b8842780/jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/mistune/ee015381e955e370962968befe1d729ab60fafb6a715ac6751763fbce38c8d4a/mistune-3.3.4-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.9/66.9 kB 6.6 MB/s eta 0:00:00
Collecting nbclient>=0.5.0 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbclient/ef7fa0d59d6e1d41103933d8a445a18d5de860ca6b613b87b8574accdb3c2895/nbclient-0.11.0-py3-none-any.whl (25 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pandocfilters/93be382804a9cdb0a7267585f157e5d1731bbe5545a85b268d6f5fe6232de2bc/pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting playwright (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/playwright/ad21bc07516b187965a7521c5cf0df0bd657b17482eaad74335272d35a2b07de/playwright-1.63.0-py3-none-manylinux1_x86_64.whl (48.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 MB 105.5 MB/s eta 0:00:0000:0100:01
Collecting fastjsonschema>=2.15 (from nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/fastjsonschema/0fb3915616adac85ccfdd737d26be1089845d2019819505b42d39888458f74d4/fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jsonschema/d489f15263b8d200f8387e64b4c3a75f06629559fb73deb8fdfb525f2dab50ce/jsonschema-4.26.0-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 9.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2026.3)
Collecting pydantic!=2.0.*,<3,>=2 (from python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pydantic/346a034f080da3755d8e9cb5e00e8b07de1d39e4f6e2c87d8ab7cafa0b269a73/pydantic-2.13.5-py3-none-any.whl (472 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.6/472.6 kB 37.6 MB/s eta 0:00:00
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (2026.7.22)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/webencodings/7fab6269c8bf237c657876b52058ccb182e861518d1c695c1a9aaa8c1c105d5b/webencodings-0.6.1-py3-none-any.whl (8.7 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/tinycss2/3415ba0f5839c062696996998176c4a3751d18b7edaaeeb658c9ce21ec150661/tinycss2-1.5.1-py3-none-any.whl (28 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jedi>=0.18.2->ipython->otter-grader) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (26.1.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jsonschema-specifications/98802fee3a11ee76ecaca44429fda8a41bff98b00a0f2838151b113f210cc6fe/jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/referencing/381329a9f99628c9069361716891d34ad94af76e461dcb0335825aecc7692231/referencing-0.37.0-py3-none-any.whl (26 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/rpds-py/136a1c3fe4402b7008bc81cb62ee538481795b61a7e83df88dff3b3f02b726ff/rpds_py-2026.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (375 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.4/375.4 kB 30.2 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jupyter-core>=4.7->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (4.11.3)
Collecting mdurl~=0.1 (from markdown-it-py>=1.0->jupytext<2.0.0,>=1.19.3->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/mdurl/84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: jupyter-client>=7.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (8.9.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pexpect>4.6->ipython->otter-grader) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->otter-grader) (0.8.2)
Collecting annotated-types>=0.6.0 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/annotated-types/f072f4d804ea359e4eaf198b1af7a8b0943881a87f31bb764f8bf219bb9419e0/annotated_types-0.8.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.46.5 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pydantic-core/49776eab08766a08dfff7012f8b422dcd7e25e43b316eedf0477c24fcfa84b7c/pydantic_core-2.46.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.8 MB/s eta 0:00:00a 0:00:010m
Collecting typing-inspection>=0.4.2 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/typing-inspection/65b8397ba37ccbce054456aaccddfc91e6e3083c92824df348d96ca832f3f147/typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->otter-grader) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (3.0.2)
Requirement already satisfied: pure_eval in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (0.2.3)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/soupsieve/8596eb8967d744174820280fa62b4542a2e955bfaccca73ed8a13c6eb8e9b502/soupsieve-2.10-py3-none-any.whl (38 kB)
Collecting pyee<14,>=13 (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pyee/af2f8fede4171ef667dfded53f96e2ed0d6e6bd7ee3bb46437f77e3b57689228/pyee-13.0.1-py3-none-any.whl (15 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/greenlet/1c20ea32a73d17b9b60e3371240e17b0068120c98a5ec01a224a7dd8c89733ba/greenlet-3.5.6-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (624 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.4/624.4 kB 41.0 MB/s eta 0:00:00
Collecting sphinxcontrib-applehelp>=1.0.7 (from sphinx->fica>=0.4.1->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/sphinxcontrib-applehelp/4cd3f0ec4ac5dd9c17ec65e9ab272c9b867ea77425228e68ecf08d6b28ddbdb5/sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.3/119.3 kB 12.2 MB/s eta 0:00:00
Collecting sphinxcontrib-devhelp>=1.0.6 (from sphinx->fica>=0.4.1->otter-grader)

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/MEDS-eds-220/eds220-hwk-1]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

This dataset includes observations of four models of climate change, water quality, direct human activities, and variable selection processes and how they influence the state of coral reefs in the Western Indian Ocean. They also provide the process and sampling section that describes the process of the data collection. Tim McClanahan. (2023). Western Indian Ocean Coral Diversity. Knowledge Network for Biocomplexity. doi:10.5063/F1K35S3H. Date of access: 10/05/2026.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [3]:
import pandas as pd
coral_div = pd.read_csv('data/coral_data.csv')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [7]:
#a
# Counting the number of rows
rows = coral_div.shape[0]

# Counting the number of columns 
columns = coral_div.shape[1]

In [8]:
grader.check("q3_a")

q3_a results: All test cases passed!

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [9]:
#b
# List all the column names
coral_div_columns = coral_div.columns.tolist()

In [10]:
grader.check("q3_b")

q3_b results: All test cases passed!

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [62]:
#c
# Lists the columns data types 
coral_div_types = coral_div.dtypes

In [16]:
grader.check("q3_c")

q3_c results: All test cases passed!

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [17]:
#d
# Shows the first 8 rows of the dataframe
first_8_rows = coral_div.head(8)

In [18]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,...,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,...,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [19]:
grader.check("q3_d")

q3_d results: All test cases passed!

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [21]:
# e
# Displays all the unique values in each column 
coral_div.nunique()

PU_ID                  304
PU_Lat                 152
PU_Lon                 217
Number_of_genera        37
Country                 11
Ecoregion                6
Management               4
Habitat                  6
Observer                16
Depth                  111
Coralcover              46
SSTRateofRise          283
PARmax                 221
Calcite                219
Dis_oxygen             187
mean.waveNRJ           237
Salinity_mean          226
andrello_reef_value    139
andrello_nutrients     165
mean.npp               197
TT_market_hrs          129
TT_pop_hrs              51
cumDHW                 283
SST_Kurtosis           283
SST_Median             193
ChlorA_median          283
andrello_sediments     180
Current_vel_mean       224
Diff_attenuation       165
Grav_NP                168
Grav_NC                169
PH                      62
SST_bimodality         282
SST_Skewness           283
ClimateStressModel     297
Netflow                126
Indegree               110
Outdegree              106
Retention              109
min_yr                  19
max_yr                  19
no_replicates           12
dtype: int64

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

int64 specifies that the type of numerical value is a whole number while float64 specifies that the value contains decimals.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

coral_div['Country'] would output a list of values from the Country column from all the rows. coral_div['Country'].unique() on the other hand, would only output all the different values in the column Country.

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [22]:
# Shows all the unique values in the column Observer
unique_observers = coral_div['Observer'].nunique()

In [23]:
grader.check("q6")

q6 results: All test cases passed!

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

This code will return Boolean values corresponding to each row in the Coralcover column.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

When you run this code, the Coralcover column will only return the values that satisfy the condition, removing the other rows from the dataframe temporarily.

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [25]:
# Filters the dataframe so that Coralcover equals 30% in Tanzania
coral_cover = coral_div[(coral_div['Coralcover'] == 30) & (coral_div['Country'] == 'Tanzania')]

In [26]:
# View the dataframe
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,...,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,...,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,...,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,...,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,...,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,...,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,...,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [27]:
grader.check("q8")

q8 results: All test cases passed!

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [31]:
# Filters only the pH, salinity mean, and depth columns
filtered_data = coral_div[['PH', 'Salinity_mean', 'Depth']]

In [32]:
# View the dataframe
filtered_data.head()

       PH  Salinity_mean  Depth
0  8.2175      35.167646   11.0
1  8.2175      35.167646    2.0
2  8.2175      35.167646    4.0
3  8.2175      35.167646    3.0
4  8.2180      35.102688    1.5

In [33]:
grader.check("q9")

q9 results: All test cases passed!

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [38]:
# Subsets the pH, salinity mean, depth, and max year column in 2017
sampling_2017 = coral_div.loc[coral_div['max_yr'] == 2017, ['PH', 'Salinity_mean', 'Depth', 'max_yr']]

In [39]:
# View the dataframe 
sampling_2017

         PH  Salinity_mean      Depth  max_yr
67   8.2150      35.100085  16.000000    2017
68   8.2145      35.144927  10.000000    2017
70   8.2150      35.101086  11.000000    2017
71   8.2150      35.101086  11.000000    2017
72   8.2150      35.101086   9.000000    2017
73   8.2150      35.101086   9.000000    2017
84   8.2110      35.278084  12.500000    2017
85   8.2110      35.278084   6.000000    2017
164  8.2220      35.337914   9.875000    2017
167  8.2220      35.337914  12.075000    2017
169  8.2220      35.337914  10.300000    2017
172  8.2220      35.337914  11.000000    2017
174  8.2225      35.287419   7.266667    2017
176  8.2225      35.287419  13.225000    2017
179  8.2225      35.287419  10.550000    2017
182  8.2220      35.331669  12.033333    2017
185  8.2230      35.374460  10.900000    2017
188  8.2230      35.374460  14.725000    2017
191  8.2230      35.247482   9.725000    2017
194  8.2230      35.341358  11.075000    2017
197  8.2230      35.390354  10.600000    2017
346  8.2165      35.114244   7.000000    2017
347  8.2165      35.112398   3.000000    2017
348  8.2165      35.112398   4.000000    2017
349  8.2160      35.117374   5.500000    2017
350  8.2160      35.117374   2.000000    2017
351  8.2160      35.117374  15.000000    2017
352  8.2160      35.117374   5.000000    2017
353  8.2165      35.149462  11.000000    2017
354  8.2160      35.270199   9.000000    2017
395  8.2400      35.276642   9.416667    2017
559  8.2120      35.204185   1.500000    2017
566  8.2400      35.301208  17.000000    2017
569  8.2400      35.301208  13.833333    2017
574  8.2400      35.301208  13.470000    2017

In [40]:
grader.check("q10")

q10 results: All test cases passed!

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [50]:
# Subsetting from row 95-100 and the 17th, 20th and 28th column 
subset = coral_div.iloc[[95, 96, 97, 98, 99, 100], [16, 19, 27]]

In [51]:
# View the dataframe
subset

     Salinity_mean     mean.npp  Current_vel_mean
95       35.201630  1365.146729          0.878417
96       35.204185  1117.635010          0.839372
97       35.234774  1105.270142          0.685955
98       35.234774  1105.270142          0.685955
99       35.250068  1082.196411               NaN
100      35.250068  1082.196411               NaN

In [52]:
grader.check("q11")

q11 results: All test cases passed!

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

In [53]:
subset.isna()

     Salinity_mean  mean.npp  Current_vel_mean
95           False     False             False
96           False     False             False
97           False     False             False
98           False     False             False
99           False     False              True
100          False     False              True

The code returns Boolean values for each row in each column. False means the values are not NaN and True means they are.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

In [54]:
subset.isna().any()

Salinity_mean       False
mean.npp            False
Current_vel_mean     True
dtype: bool

This code returns a single Boolean value for each column. It tells us if there is at least one NaN in the column, it will return True.

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [58]:
# 
subset_na = subset[subset['Current_vel_mean'].isna()]

In [59]:
# View the dataframe 
subset_na

     Salinity_mean     mean.npp  Current_vel_mean
99       35.250068  1082.196411               NaN
100      35.250068  1082.196411               NaN

In [60]:
grader.check("q14")

q14 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [61]:
grader.check_all()

q10 results: All test cases passed!

q11 results: All test cases passed!

q14 results: All test cases passed!

q3_a results: All test cases passed!

q3_b results: All test cases passed!

q3_c results: All test cases passed!

q3_d results: All test cases passed!

q6 results: All test cases passed!

q8 results: All test cases passed!

q9 results: All test cases passed!